#!/bin/bash

system_type=$(uname -s)

bootstrap() {
  install_brew

  echo "=> upgrade all packages"
  brew upgrade > /dev/null 2>&1

  echo "=============| begin install group | ============="

  echo "=| core"
  install curl
  install git
  install_zplug

  echo "=| dotfiles"
  install yadm
  dotfiles

  echo "=| fonts"
  install homebrew/cask-fonts/font-hack

  echo "=| terminal"
  install_kitty

  echo "=| lang env"
  install_rust

  echo "=| editors"

  install neovim
  install_vim_manager

  echo "=| deployment"

  install kubectl
  install helm

  echo "=| shell"
  install ripgrep
  install fzf
  install tig
  install tree
  install htop

  echo "=| utilities"
  install editorconfig
  install gnupg

  echo "=============| end install group | ============="
}

# =============================================================================

command_exists()
{
  command -v "$1" >/dev/null 2>&1
}

install_brew()
{
  echo "=| brew"
  if ! command_exists brew; then
    echo "=> install"
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" >/dev/null 2>&1
  fi
  brew update > /dev/null 2>&1
}

install()
{
  echo "==| $1"
  if ! brew ls $1 >/dev/null 2>&1; then
    if ! brew cask ls $1 >/dev/null 2>&1; then
      brew install $1 > /dev/null
    fi
  fi
}

clone_pull()
{
  (git -C $2 pull || git clone $1 $2) >/dev/null 2>&1
}

install_zplug()
{
  echo "==| zplug"
  if [ ! -d "$HOME/.zplug" ]; then
    curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh
  else
    echo "==> update"
    clone_pull git@github.com:zplug/zplug.git "$HOME/.zplug"
  fi
}

dotfiles()
{
  if [ ! -d "$HOME/.config/yadm/repo.git" ]; then
    echo "===| clone"
    yadm clone -f --no-bootstrap git@github.com:alexfridlyand/dotfiles.git >/dev/null 2>&1
  else
    echo "===| pull"
    yadm pull >/dev/null 2>&1
  fi
}

install_kitty()
{
  echo "==| kitty"
  curl -sL https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin \
    launch=n >/dev/null 2>&1
}

install_rust()
{
  echo "==| rust"
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y > /dev/null 2>&1
}

install_vim_manager()
{
  echo "===| plug"
  curl -sL https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh > /tmp/installer.sh
  sh /tmp/installer.sh $HOME/.local/share/dein >/dev/null 2>&1
  bash $HOME/.config/yadm/vimup
}

bootstrap
